---
title: "introduction"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{introduction}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---
```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

Esse pacote deve usado da seguinte forma:

# Lendo arquivos do dropbox ou localmente, atualizando arquivo local se diferente
```{r setup}
library(GEESCHelpersR)
local_path <- "/local/path.csv"
drop_path <- "/dropbox/path.csv"
dbx <- get_dropbox_access_token("/path/to/.env")

file <- dbx %>%
  try_download(dropbox_path, local_path) %>%
  # function to read the file
  read.csv()
```

# Lendo do Dropbox ou localmente para arquivos .zip com shapefiles
```{r setup}
library(GEESCHelpersR)
local_path <- "/local/path.csv"
drop_path <- "/dropbox/path.csv"
dbx <- get_dropbox_access_token("/path/to/.env")

file <- dbx %>%
  try_sf_download(dropbox_path, local_path) %>%
  # function to read the file
  read.csv()
```

# Baixando do Dropbox somente para o disco
```{r setup}
library(GEESCHelpersR)
local_path <- "/local/path.csv"
drop_path <- "/dropbox/path.csv"
dbx <- get_dropbox_access_token("/path/to/.env")

dbx %>%
  download_dropbox_file(drop_path, local_path)
```

# Lendo do Dropbox somente para a memória
```{r setup}
library(GEESCHelpersR)

drop_path <- "/dropbox/path.csv"
dbx <- get_dropbox_access_token("/path/to/.env")

dbx %>%
  download_dropbox_memory(drop_path) %>%
  # function to read the file
  read.csv()
```
